/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionNameRouteImport } from './routes/session.$name'
import { Route as SessionNameSchemeRouteImport } from './routes/session.$name.scheme'
import { Route as SessionNameResultsRouteImport } from './routes/session.$name.results'
import { Route as SessionNameImportRouteImport } from './routes/session.$name.import'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNameRoute = SessionNameRouteImport.update({
  id: '/session/$name',
  path: '/session/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNameSchemeRoute = SessionNameSchemeRouteImport.update({
  id: '/scheme',
  path: '/scheme',
  getParentRoute: () => SessionNameRoute,
} as any)
const SessionNameResultsRoute = SessionNameResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SessionNameRoute,
} as any)
const SessionNameImportRoute = SessionNameImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SessionNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/session/$name': typeof SessionNameRouteWithChildren
  '/session/$name/import': typeof SessionNameImportRoute
  '/session/$name/results': typeof SessionNameResultsRoute
  '/session/$name/scheme': typeof SessionNameSchemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/session/$name': typeof SessionNameRouteWithChildren
  '/session/$name/import': typeof SessionNameImportRoute
  '/session/$name/results': typeof SessionNameResultsRoute
  '/session/$name/scheme': typeof SessionNameSchemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/session/$name': typeof SessionNameRouteWithChildren
  '/session/$name/import': typeof SessionNameImportRoute
  '/session/$name/results': typeof SessionNameResultsRoute
  '/session/$name/scheme': typeof SessionNameSchemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/session/$name'
    | '/session/$name/import'
    | '/session/$name/results'
    | '/session/$name/scheme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/session/$name'
    | '/session/$name/import'
    | '/session/$name/results'
    | '/session/$name/scheme'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/session/$name'
    | '/session/$name/import'
    | '/session/$name/results'
    | '/session/$name/scheme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SessionNameRoute: typeof SessionNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$name': {
      id: '/session/$name'
      path: '/session/$name'
      fullPath: '/session/$name'
      preLoaderRoute: typeof SessionNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$name/scheme': {
      id: '/session/$name/scheme'
      path: '/scheme'
      fullPath: '/session/$name/scheme'
      preLoaderRoute: typeof SessionNameSchemeRouteImport
      parentRoute: typeof SessionNameRoute
    }
    '/session/$name/results': {
      id: '/session/$name/results'
      path: '/results'
      fullPath: '/session/$name/results'
      preLoaderRoute: typeof SessionNameResultsRouteImport
      parentRoute: typeof SessionNameRoute
    }
    '/session/$name/import': {
      id: '/session/$name/import'
      path: '/import'
      fullPath: '/session/$name/import'
      preLoaderRoute: typeof SessionNameImportRouteImport
      parentRoute: typeof SessionNameRoute
    }
  }
}

interface SessionNameRouteChildren {
  SessionNameImportRoute: typeof SessionNameImportRoute
  SessionNameResultsRoute: typeof SessionNameResultsRoute
  SessionNameSchemeRoute: typeof SessionNameSchemeRoute
}

const SessionNameRouteChildren: SessionNameRouteChildren = {
  SessionNameImportRoute: SessionNameImportRoute,
  SessionNameResultsRoute: SessionNameResultsRoute,
  SessionNameSchemeRoute: SessionNameSchemeRoute,
}

const SessionNameRouteWithChildren = SessionNameRoute._addFileChildren(
  SessionNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SessionNameRoute: SessionNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
