/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as GlobalBankRouteImport } from './routes/global-bank'
import { Route as CombineRouteImport } from './routes/combine'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamNameRouteImport } from './routes/exam.$name'
import { Route as ExamNameIndexRouteImport } from './routes/exam.$name.index'
import { Route as ExamNameTableRouteImport } from './routes/exam.$name.table'
import { Route as ExamNameSchemeRouteImport } from './routes/exam.$name.scheme'
import { Route as ExamNameResultsRouteImport } from './routes/exam.$name.results'
import { Route as ExamNamePdfRouteImport } from './routes/exam.$name.pdf'
import { Route as ExamNameImportRouteImport } from './routes/exam.$name.import'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalBankRoute = GlobalBankRouteImport.update({
  id: '/global-bank',
  path: '/global-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const CombineRoute = CombineRouteImport.update({
  id: '/combine',
  path: '/combine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamNameRoute = ExamNameRouteImport.update({
  id: '/exam/$name',
  path: '/exam/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamNameIndexRoute = ExamNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamNameRoute,
} as any)
const ExamNameTableRoute = ExamNameTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => ExamNameRoute,
} as any)
const ExamNameSchemeRoute = ExamNameSchemeRouteImport.update({
  id: '/scheme',
  path: '/scheme',
  getParentRoute: () => ExamNameRoute,
} as any)
const ExamNameResultsRoute = ExamNameResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ExamNameRoute,
} as any)
const ExamNamePdfRoute = ExamNamePdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ExamNameRoute,
} as any)
const ExamNameImportRoute = ExamNameImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ExamNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/global-bank': typeof GlobalBankRoute
  '/new': typeof NewRoute
  '/exam/$name': typeof ExamNameRouteWithChildren
  '/exam/$name/import': typeof ExamNameImportRoute
  '/exam/$name/pdf': typeof ExamNamePdfRoute
  '/exam/$name/results': typeof ExamNameResultsRoute
  '/exam/$name/scheme': typeof ExamNameSchemeRoute
  '/exam/$name/table': typeof ExamNameTableRoute
  '/exam/$name/': typeof ExamNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/global-bank': typeof GlobalBankRoute
  '/new': typeof NewRoute
  '/exam/$name/import': typeof ExamNameImportRoute
  '/exam/$name/pdf': typeof ExamNamePdfRoute
  '/exam/$name/results': typeof ExamNameResultsRoute
  '/exam/$name/scheme': typeof ExamNameSchemeRoute
  '/exam/$name/table': typeof ExamNameTableRoute
  '/exam/$name': typeof ExamNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/global-bank': typeof GlobalBankRoute
  '/new': typeof NewRoute
  '/exam/$name': typeof ExamNameRouteWithChildren
  '/exam/$name/import': typeof ExamNameImportRoute
  '/exam/$name/pdf': typeof ExamNamePdfRoute
  '/exam/$name/results': typeof ExamNameResultsRoute
  '/exam/$name/scheme': typeof ExamNameSchemeRoute
  '/exam/$name/table': typeof ExamNameTableRoute
  '/exam/$name/': typeof ExamNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combine'
    | '/global-bank'
    | '/new'
    | '/exam/$name'
    | '/exam/$name/import'
    | '/exam/$name/pdf'
    | '/exam/$name/results'
    | '/exam/$name/scheme'
    | '/exam/$name/table'
    | '/exam/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combine'
    | '/global-bank'
    | '/new'
    | '/exam/$name/import'
    | '/exam/$name/pdf'
    | '/exam/$name/results'
    | '/exam/$name/scheme'
    | '/exam/$name/table'
    | '/exam/$name'
  id:
    | '__root__'
    | '/'
    | '/combine'
    | '/global-bank'
    | '/new'
    | '/exam/$name'
    | '/exam/$name/import'
    | '/exam/$name/pdf'
    | '/exam/$name/results'
    | '/exam/$name/scheme'
    | '/exam/$name/table'
    | '/exam/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombineRoute: typeof CombineRoute
  GlobalBankRoute: typeof GlobalBankRoute
  NewRoute: typeof NewRoute
  ExamNameRoute: typeof ExamNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-bank': {
      id: '/global-bank'
      path: '/global-bank'
      fullPath: '/global-bank'
      preLoaderRoute: typeof GlobalBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combine': {
      id: '/combine'
      path: '/combine'
      fullPath: '/combine'
      preLoaderRoute: typeof CombineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$name': {
      id: '/exam/$name'
      path: '/exam/$name'
      fullPath: '/exam/$name'
      preLoaderRoute: typeof ExamNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$name/': {
      id: '/exam/$name/'
      path: '/'
      fullPath: '/exam/$name/'
      preLoaderRoute: typeof ExamNameIndexRouteImport
      parentRoute: typeof ExamNameRoute
    }
    '/exam/$name/table': {
      id: '/exam/$name/table'
      path: '/table'
      fullPath: '/exam/$name/table'
      preLoaderRoute: typeof ExamNameTableRouteImport
      parentRoute: typeof ExamNameRoute
    }
    '/exam/$name/scheme': {
      id: '/exam/$name/scheme'
      path: '/scheme'
      fullPath: '/exam/$name/scheme'
      preLoaderRoute: typeof ExamNameSchemeRouteImport
      parentRoute: typeof ExamNameRoute
    }
    '/exam/$name/results': {
      id: '/exam/$name/results'
      path: '/results'
      fullPath: '/exam/$name/results'
      preLoaderRoute: typeof ExamNameResultsRouteImport
      parentRoute: typeof ExamNameRoute
    }
    '/exam/$name/pdf': {
      id: '/exam/$name/pdf'
      path: '/pdf'
      fullPath: '/exam/$name/pdf'
      preLoaderRoute: typeof ExamNamePdfRouteImport
      parentRoute: typeof ExamNameRoute
    }
    '/exam/$name/import': {
      id: '/exam/$name/import'
      path: '/import'
      fullPath: '/exam/$name/import'
      preLoaderRoute: typeof ExamNameImportRouteImport
      parentRoute: typeof ExamNameRoute
    }
  }
}

interface ExamNameRouteChildren {
  ExamNameImportRoute: typeof ExamNameImportRoute
  ExamNamePdfRoute: typeof ExamNamePdfRoute
  ExamNameResultsRoute: typeof ExamNameResultsRoute
  ExamNameSchemeRoute: typeof ExamNameSchemeRoute
  ExamNameTableRoute: typeof ExamNameTableRoute
  ExamNameIndexRoute: typeof ExamNameIndexRoute
}

const ExamNameRouteChildren: ExamNameRouteChildren = {
  ExamNameImportRoute: ExamNameImportRoute,
  ExamNamePdfRoute: ExamNamePdfRoute,
  ExamNameResultsRoute: ExamNameResultsRoute,
  ExamNameSchemeRoute: ExamNameSchemeRoute,
  ExamNameTableRoute: ExamNameTableRoute,
  ExamNameIndexRoute: ExamNameIndexRoute,
}

const ExamNameRouteWithChildren = ExamNameRoute._addFileChildren(
  ExamNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombineRoute: CombineRoute,
  GlobalBankRoute: GlobalBankRoute,
  NewRoute: NewRoute,
  ExamNameRoute: ExamNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
